FROM ubuntu:22.04

# RUN apt-get update && apt-get install -y \
#    libssl-dev \
#    libpq-dev \
#    ca-certificates \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./build/bin/MatchingServer .

EXPOSE 8080

RUN chmod +x ./MatchingServer

CMD ["/app/MatchingServer"]
